### ISSUE TITLE
Allow option to skip iframe injection

### ISSUE THREAD

**Issue by renatoi** [dequelabs/axe-selenium-java#10]
Hi,

Is it possible to add an option to skip the following line?
https://github.com/dequelabs/axe-selenium-java/blob/master/src/main/java/com/deque/axe/AXE.java#L72

The main reason is because this call is super slow. It's currently preventing me to use this in our CI pipeline because it's adding extra 30s for each page just to execute this line:

https://github.com/dequelabs/axe-selenium-java/blob/9b2cabcd8611c29448654422bec70c18a6aa3735/src/main/java/com/deque/axe/AXE.java#L87

**Comment by WilcoFiers** [comment]
Is it that line itself that's slowing this down, or are the frames taking this long to test?

**Comment by renatoi** [comment]
I've confirmed that it's just this line that is taking too long to run, not sure why. Everything else, at the moment, seems to be working fine.

**Comment by WilcoFiers** [comment]
@renatoi That is quite strange indeed. Do you want to work on a pull request for this? If not we'll put it on our backlog, but it is a little long, fair warning ;).
