### ISSUE TITLE
document-title and html-has-lang

### ISSUE THREAD

**Issue by longmatthewh** [dequelabs/axe-selenium-java#12]
Not sure if I'm doing something wrong here, but I'm seeing document-title and html-has-lang issues even though the lang attribute is set and the document has a title.

**Comment by WilcoFiers** [comment]
Are there any frames on the page? Have a look at the selectors to see what element might have failed.

**Comment by longmatthewh** [comment]
Thanks @WilcoFiers! There is an iframe on the page from Google Classroom. I'll disable these for now.
