### ISSUE TITLE
Can I Run only Rules for an accessibility standard? For eg: WCAG 2.0 Level A and exclude WCAG 2.0 Level AA. This is similar to using .runonly option of axe.configure in axe-core? How can I achieve this in the test I am running in ExampleTest.java here in axe-selenium-java?  Thank you!

### ISSUE THREAD

**Issue by tejeshvi** [dequelabs/axe-selenium-java#13]

**Comment by dmfay** [comment]
Yes, you can set `runOnly` with the `options` builder method. Look at the readme and the [testAccessibilityWithOptions](https://github.com/dequelabs/axe-selenium-java/blob/master/src/test/java/com/deque/axe/ExampleTest.java#L98) example testcase for more.
