### ISSUE TITLE
Support axe-core 3.0

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-selenium-java#15]
As mentioned here: https://github.com/dequelabs/axe-core/issues/833

This project does not yet support axe-core 3.0.

**Comment by rajudevjava** [comment]
@WilcoFiers I understand that axe-core 3.0 is not supported for axe-selenium-java, but, is there way to run axe 3.0 version using selenium-java automation?

**Comment by marcysutton** [comment]
@rajudevjava there isn't yet. You could install a newer version than 2.0.5 (but still prior to 3.0, which had breaking API changes) by downloading it from a CDN: https://cdnjs.cloudflare.com/ajax/libs/axe-core/2.6.1/axe.js

**Comment by rajudevjava** [comment]
@marcysutton Thanks for the information. 
I know you were referring to axe.js file for v2.6.1 but, as we were using axe.min.js file in our project, I searched for this online as was able to get axe.min.js file from below link.
"https://www.cdnpkg.com/axe-core/file/axe.min.js/" . Also, the Axe.java file we are still using is from axe-selenium-java project.  Is there a Axe.java file for v2.6.1 ?

Also, could you please brief up about the above disclaimer you were referring to?

**Comment by marcysutton** [comment]
@rajudevjava That CDN should work fine, as long as you're using an older axe-core version (pre-3.0). axe-selenium-java was designed to allow you to swap out minor or patch axe-core versions but the API hasn't been updated to work yet with axe-core@3.0. You'll have to wait for the Java project to be updated, which is what this issue is about.

**Comment by rajudevjava** [comment]
Can this request be prioritized as we have an urgent need to upgrade our project to aXe v3.0.0 . Thanks!

**Comment by kavmaria** [comment]
Is it possible to downgrade to an older axe-core version 2.6.1?

**Comment by DavidMacDonald** [comment]
I'd vote for support for Axe Core version 3.0 also.

**Comment by Logan-Lim** [comment]
I am also interested in leveraging this project with axe-core 3.x

The current develop branch seems to function correctly with axe-core 3.1.2. Are there any remaining tasks in order to do a new release?
