### ISSUE TITLE
require is not defined

### ISSUE THREAD

**Issue by rajudevjava** [dequelabs/axe-selenium-java#16]
Trying to combine this project with webdriverjs for aXe 3.0.0. I have selenium java project which navigates through web pages. After navigating to a page, I'm calling a js file named as test.js with AxeBuilder defined in it. I'm getting an error "require" is not defined in <eval> at line number 1". Is there a way to get this worked?

**Comment by stephenmathieson** [comment]
The develop branch now as axe v3 in it and we're not seeing this error. Closing for now.

Feel free to reopen with more details.
