### ISSUE TITLE
feature request: configurable timeout

### ISSUE THREAD

**Issue by swathi-prasad** [dequelabs/axe-selenium-java#17]
Hello, I am facing issues with accessibility using aXe for one of my webpages. Apparently the DOM for the webpage is too huge for the aXe tool to perform accessibility. My script is timing out after 30seconds. Is there any input limit set for the aXe tool? Please advise. #17

**Comment by stephenmathieson** [comment]
Adding a configurable timeout seems like a very reasonable feature to add. I'll look into this today.
