### ISSUE TITLE
aXe selenium java v3.0.0 alpha.9 - TypeError: axe.run arguments are invalid

### ISSUE THREAD

**Issue by rajudevjava** [dequelabs/axe-selenium-java#19]
Hello,

Upgraded aXe for selenium java version to 3.0.0 (axe.min.js , test-app.js and AXE.java). receiving below error during execution. 
![capture](https://user-images.githubusercontent.com/11168455/45574065-b50ee180-b83c-11e8-9cc1-ba236bdaad5e.PNG)

**Comment by stephenmathieson** [comment]
I'm not able to reproduce this. Do you have any more details?

**Comment by stephenmathieson** [comment]
Closing for now. If you're still experiencing this problem, please feel free reopen with reproduction steps.
