### ISSUE TITLE
Violation does not captured for mobile simulator/devices

### ISSUE THREAD

**Issue by mchoyal** [dequelabs/axe-selenium-java#20]

**Comment by WilcoFiers** [comment]
Please provide some details for this issue so we can reproduce it.

**Comment by mchoyal** [comment]
I am running my tests using AXE lib, with Java/Selenium for desktop web, its capturing violations when I run my test on chrome browser on desktop machine. But when I tried to run similar tests on Android/iOS simulators using Appium/Selenium (After integrating AXE lib) than it does not capture the violations. Not sure if it support mobile simulators?

**Comment by WilcoFiers** [comment]
Ahhh that makes sense. Axe is not build to test mobile apps, it is an HTML testing tool. The platforms are too different that a single testing tool can't do it. There are a few accessibility tools that test mobile that you can use. Deque, the company behind axe-core has one called Attest. It has different testing tools for HTML, iOS and Android. You can find information about it here:

- https://www.deque.com/tools/worldspace-attest/
- https://accessibility.deque.com/ios-accessibility-testing-free-trial

Hope that helps. Closing the issue as there is no action to follow up on.
