### ISSUE TITLE
Did not get all violations which are captured through chrome AXE plugin

### ISSUE THREAD

**Issue by mchoyal** [dequelabs/axe-selenium-java#21]
Dear Team,

I tried using axe-selenium-java lib to get all violations on my webpage, but it does not capture all violations, however those were captured in chrome AXE plugin. 

How can we capture all violations using axe-selenium-java lib? For example: we got "Banner landmark must not be contained in another landmark" violation on chrome AXE plugin, but its ignored when I used axe-selenium-java lib.

Thanks,
Manak

**Comment by stephenmathieson** [comment]
This is likely due to conflicting axe-core versions. Closing for now.

Reopen if this is still a problem.

**Comment by PriyalakshmiNandan** [comment]
Hi Stephen,

  My Chrome add-on Axe extension gave me a different set of violations [V3.2.2] while Axe-selenium plugin have logged different set of violations [V 3.0] & I do find the Axe-selenium does not have dependency on Axe-core plugin. can you guide how make both log similar set of Violations? Does both Chrome Extension-Axe-V 3.2.2 and Axe-Selenium-V 3.0 points to same version of Axe-core?

Regards,
Priya
