### ISSUE TITLE
Implement Marionette Driver in ExampleTest.java

### ISSUE THREAD

**Issue by dmhalejr** [dequelabs/axe-selenium-java#6]
Hello All!

Mozilla has taken over development of the FirefoxDriver from Selenium and have started implementing Marionette starting around Firefox 46.0. 

What that means is that users may start running into:

```
Selenium::WebDriver::Error::WebDriverError: unable to obtain stable firefox connection in 60 seconds
```

Unless implementing the GeckoDriver like so: 
https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/WebDriver

Wonderful accessibility tool I'm now leveraging! :clap: 

Will be shouting out in coming up user group presentation.

**Comment by bgoldowsky** [comment]
I can confirm that this does not run with current Firefox 52 on Mac.

An update to Selenium 3 would be nice, and perhaps to latest aXe version as well?

For the moment, I was able to get it to work by switching to ChromeDriver.

**Comment by stephenmathieson** [comment]
Is this still an issue? We're using Selenium 3 and axe 3 now.

**Comment by stephenmathieson** [comment]
Closing for now. If you're still experiencing this problem, please feel free reopen with reproduction steps.
