### ISSUE TITLE
axe update for java

### ISSUE THREAD

**Issue by sauravkumar05** [dequelabs/axe-selenium-java#9]
Hey guys - i see that the core is getting updated for javascript related projects but not for java. Is there any plan to update the java project which is this one .  I have been using axe for running report violations and i see difference in result when i run a plugin via chrome Vs via java code.

**Comment by dylanb** [comment]
you can simply download the axe-core version from npmjs.org and oevrwrite the `axe.min.js` file in the resources folder

**Comment by sauravkumar05** [comment]
I did that but then also i was seeing some difference. So i had downloaded the axe-core@latest and i took the axe.min.js (aXe v2.3.1) and pasted as part of my resources.

If i run the axe plugin via chrome then i see 13 violations but if i run analyze on the same page via code then i see total number as 8 voilations 
![image](https://user-images.githubusercontent.com/11820297/29798236-d2b4e9c2-8c29-11e7-92ac-3ea4ab06cac7.png)

running via java code
JSONObject responseJSON = new AXE.Builder(this.driver, this.getClass().getResource("/axe.min.js")).analyze();
			JSONArray violations = responseJSON.getJSONArray("violations");
			if (violations.length() != 0) {
				AXE.writeResults("build/AccessibilityReport/" + pageName + "_" + i, responseJSON);
				File file = new File("build/AccessibilityReport/Accessibility-violations_for_" + pageName + "_" + i + ".txt");
				FileUtils.writeStringToFile(file, AXE.report(violations), "UTF-16");
				i++;
				currentScenario.write("Accessibility Violations found with AXE - Report Created as " + pageName + "_" + i + ".json and violations created in " + "Accessibility-violations_for_" + pageName + "_" + i + ".txt");
			}

**Missing voilation compared to chrome plugin is this one -  Elements must have sufficient color contrast
 Inspect Node Highlight

**Comment by sauravkumar05** [comment]
In violations report  I see that the api rules is pointing to 2.0 but my min.js is 2.3. How can i make sure that i my app is using the 2.3 rules.

https://dequeuniversity.com/rules/axe/2.0/duplicate-id?application=axeAPI

**Comment by sauravkumar05** [comment]
In IT most of the issues are because of human error and this one was because of me. I was updating my framework code but wasnt updating the application code pom.xml with the latest version

**Comment by dylanb** [comment]
@sauravkumar05 can we close this issue?

**Comment by bgoldowsky** [comment]
It's already closed. I feel like a note in the README pointing to where the most recent axe.min.js can be found would be very helpful though, if the one bundled with this code is not going to be updated.

**Comment by rajudevjava** [comment]
@sauravkumar05  Could you tell me the aXe version you're using currently for axe-selenium-java? I'm currently using v2.6.1. Is there anything greater that you're using?
